version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8887:8887"
    volumes:
      - ./service/chat/api/etc/chat-api.yaml:/etc/chat-api.yaml
    privileged: true
    restart: always
    networks:
      - chat_network
  redis:
    container_name: redis7
    image: redis:7
    ports:
      - "46379:6379"
    volumes:
      - ./build/redis/redis.conf:/etc/redis/redis.conf
      - ./build/redis/data:/data
    environment:
      TZ: Asia/Shanghai
    networks:
      - chat_network
    restart: always
    command: redis-server /etc/redis/redis.conf
  mysql:
    container_name: mysql57
    image: mysql:5.7
    ports:
      - "43306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'chat'
      MYSQL_PASSWORD: '123456'
    volumes:
      - ./build/mysql/data:/var/lib/mysql
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - chat_network
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
networks:
  chat_network: